In [4]:
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score

## Gender/Belletristik

## Haltung zu Gender

In [5]:
def clean(x):
    r = []
    for n in x:
        if n.startswith("k"):
            r.append("k")
            continue
        if n.startswith("p"):
            r.append("p")
            continue
        if n.startswith("an") or n.startswith("f"):
            r.append("a")
            continue
        if n.startswith("am") or n.startswith("n") or n.startswith("g"):
            r.append("n")
            continue
        print(n)
    return r

In [9]:
data = pd.read_csv("evaldata/haltung.tsv", sep="\t")

tab = []
for m in set(data["model"]):
    s = []
    for r in [1,2,3,4,5]:

        s.append(f1_score(clean(list(data[(data.model == m) & (data.run == r)].true)), list(clean(data[(data.model == m) & (data.run == r)].Haltung)),  average="weighted"))

    tab.append([m, np.mean(s), np.std(s)])

tab = pd.DataFrame(tab, columns=["model","mean","std"]).sort_values("mean", ascending=False)
tab.sort_values("mean", ascending=False)

                                  model      mean       std
3                             openai/o1  0.750966  0.030826
7   deepseek/deepseek-chat-v3-0324:free  0.731546  0.033458
0                   openai/gpt-4.1-mini  0.715501  0.032022
8        deepseek/deepseek-r1-0528:free  0.697440  0.049321
11                       openai/gpt-4.1  0.685475  0.014656
6               google/gemini-2.5-flash  0.671615  0.055127
1                 google/gemini-2.5-pro  0.664223  0.044155
2                         openai/gpt-4o  0.641698  0.020199
10            anthropic/claude-sonnet-4  0.619287  0.026622
9            anthropic/claude-3.5-haiku  0.572263  0.021403
4                           x-ai/grok-4  0.566615  0.116741
5                    openai/gpt-4o-mini  0.563149  0.030470